ALTER TABLE BOOKS ADD COLUMN THUMBNAIL text;
ALTER TABLE BOOKS ADD COLUMN SMALL_THUMBNAIL text;
ALTER TABLE BOOKS ADD COLUMN WEB_READER_LINK text;
ALTER TABLE BOOKS ADD COLUMN PUBLISHER text;
ALTER TABLE BOOKS ADD COLUMN PUBLISH_DATE text;
ALTER TABLE BOOKS ADD COLUMN PAGES integer;
ALTER TABLE BOOKS ADD COLUMN ISBN text;
ALTER TABLE BOOKS ADD COLUMN DESCRIPTION text;
